### ISSUE TITLE
Recommendation: Add JSON Validator Link

### ISSUE THREAD

**Issue by frakman1** [Degederon/HouseRulesGuide#5]
In Section "**18.2. Tshooting - Failed to import**"
It might be a good idea to include a link to a JSON validator like this one:

https://jsonformatter.curiousconcept.com/

You can drag and drop your custome ruleset JSON file and have it validate it for you and highlight any errors.

## $\textcolor{Green}{Example\ of\ valid\ JSON:}$

![image](https://github.com/Degederon/HouseRulesGuide/assets/5826484/fd5fcad0-86ca-44a2-be84-42c21445056a)

## $\textcolor{Red}{Example\ of\ invalid\ JSON:}$

![image](https://github.com/Degederon/HouseRulesGuide/assets/5826484/7e573aba-ad8c-416d-a120-c0abbbd86299)

**Comment by Degederon** [comment]
Thank you so much for your feedback. I have included it in the latest version of the guide.
